-- Размеры мира
WORLD_WIDTH = 1400
WORLD_HEIGHT = 800

-- Размеры островов
ISLAND_WIDTH = 200
ISLAND_HEIGHT = 150

-- Параметры игрока
PLAYER_SIZE = 20
PLAYER_SPEED = 175
PLAYER_MAX_HEALTH = 100

-- Параметры врага
ENEMY_SIZE = 20
ENEMY_SPEED = 100
ENEMY_HEALTH = 50
ENEMY_DAMAGE = 10
ENEMY_ATTACK_COOLDOWN = 1.0

-- Блоки
BLOCK_SIZE = 30
BREAK_TIME = 1.0

-- Сердечки
HEART_SPACING = 4

-- Настройки магазина
BLOCK_PRICE_IRON = 4
SWORD_PRICE_GOLD = 10
ARMOR_PRICE_GOLD = 5
PICKAXE_PRICE_GOLD = 8

-- Ресурсы
RESOURCE_SPAWN_INTERVAL = 3
RESOURCE_COLLECT_DISTANCE = 25