name: Build LÖVE Game

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build LÖVE Project
        uses: nhartland/love-build@master
        with:
          app_name: 'Название_твоей_игры'  # Замени на свое название
          love_version: '11.5'             # Или версию, которую используешь
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: built-applications
          path: 'release'
