name: Build LÖVE Game

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build LÖVE Project
        uses: love-actions/build@v1
        with:
          app_name: 'Miniwars'
          love_version: '11.5'
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: 'release'
